<?xml version="1.0"?>

<robot name="Ruban_GNSS_Car" xmlns:xacro="http://ros.org/wiki/xacro"
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
  <!--xacro:include filename="$(find $(find ruban_sim)/urdf/common_properties.xacro"/-->
  <xacro:include filename="$(find ruban_gnss_sim)/urdf/ruban_gnss_car.gazebo.xacro"/>



  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>




  <!-- Base Size -->
  <property name="base_x_size" value="0.54" />
  <property name="base_y_size" value="0.46" />
  <property name="base_z_size" value="0.045" />

  <xacro:property name="base_mass" value="20.0" />

  <xacro:property name="base_x_offset" value="${(base_x_size/2)}"/>
  <xacro:property name="base_y_offset" value="${(base_y_size/2)}"/>
  <xacro:property name="base_z_offset" value="0.12"/>

  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.03" />
  <xacro:property name="wheel_radius" value="0.1" />
  <xacro:property name="wheel_mass" value="1.0" />
  <xacro:property name="small_wheel_length" value="0.025" />
  <xacro:property name="small_wheel_radius" value="0.0375" />
  <xacro:property name="small_wheel_mass" value="0.5" />
  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="0" />
  <xacro:property name="track" value="0.410" />
  <xacro:property name="wheel_vertical_offset" value="${wheel_radius-base_z_offset}" />
  <xacro:property name="small_wheelbase" value="0.48" />
  <xacro:property name="small_track" value="0.26" />
  <xacro:property name="small_wheel_vertical_offset" value="${small_wheel_radius-base_z_offset}" />
  <!-- macro -->
    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="box_geometry" params="width length height">
        <geometry>
            <box size="${width} ${length} ${height}"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="cylinder_geometry" params="length radius">
        <geometry>
            <cylinder length="${length}" radius="${radius}"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="default_origin" params="xyz rpyaw">
        <origin xyz="${xyz}" rpy="${rpyaw}"/>
    </xacro:macro>




<!-- base -->
  
   <link name="base_link">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="0.46 0.28 0.2" />
        </geometry>
      </visual>
       <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.46 0.28 0.2" />
        </geometry>
      </collision>
      <xacro:default_inertial mass="1.0"/>
    </link>

    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_footprint" />
      <child link="base_link" />
    </joint>

<!--  lidar  -->
     <link name="RoboPeak">
	    <visual>
	        <origin xyz="0 0 0" rpy="0 0 3.14159" />
	 	    <geometry>
		        <box size="0.02 0.02 0.02" />
		    </geometry>
	    </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                    <geometry>
		        <box size="0.02 0.02 0.02" />
                    </geometry>
            </collision>
		      <xacro:default_inertial mass="0.02"/>
    	</link>
    	<!--Attach RoboPeak_base to the laser_base-->
    	<joint name="RoboPeak_joint" type="fixed">
	    <parent link="laser_base_link" />
	    <child link="RoboPeak"/>
	    <origin xyz="0 0 0.02" rpy="0 0 0" />
    	</joint>

      <link name="laser_base_link">
	<visual>
	    <origin xyz="0 0 0" rpy="0 0 0" />
	 	<geometry>
		    <box size="0.02 0.02 0.02" />
		</geometry>
	</visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                    <geometry>
		    <box size="0.02 0.02 0.02" />
                    </geometry>
            </collision>
	    <xacro:default_inertial mass="0.02"/>
       </link>
    <!--Attach laser base to the base_link-->
       <joint name="laser_base_joint" type="fixed">
	<parent link="base_link" />
	<child link="laser_base_link"/>
	<origin xyz="0 0 0.11" rpy="0 0 0" />
       </joint>



<!--  rtk1  -->
     <link name="RTK_1">
	    <visual>
	        <origin xyz="0 0 0" rpy="0 0 0" />
	 	    <geometry>
		        <cylinder radius="0.03" length="0.02"/>
		    </geometry>
	    </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                    <geometry>
		        <cylinder radius="0.03" length="0.02"/>
                    </geometry>
            </collision>
		      <xacro:default_inertial mass="0.002"/>
    	</link>
    	<!--Attach RoboPeak_base to the laser_base-->
    	<joint name="RTK_1_joint" type="fixed">
	    <parent link="base_link" />
	    <child link="RTK_1"/>
	    <origin xyz="0.19 0 0.11" rpy="0 0 0" />
    	</joint>




<!--  rtk2  -->
     <link name="RTK_2">
	    <visual>
	        <origin xyz="0 0 0" rpy="0 0 0" />
	 	    <geometry>
		        <cylinder radius="0.03" length="0.02"/>
		    </geometry>
	    </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                    <geometry>
		        <cylinder radius="0.03" length="0.02"/>
                    </geometry>
            </collision>
		      <xacro:default_inertial mass="0.002"/>
    	</link>
    	<!--Attach RoboPeak_base to the laser_base-->
    	<joint name="RTK_2_joint" type="fixed">
	    <parent link="base_link" />
	    <child link="RTK_2"/>
	    <origin xyz=" -0.19 0 0.11" rpy="0 0 0" />
    	</joint>





<!--  cam1  -->
     <link name="camera_1">
	    <visual>
	        <origin xyz="0 0 0" rpy="0 1.5707 0" />
	 	    <geometry>
		        <cylinder radius="0.01" length="0.005"/>
		    </geometry>
	    </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 1.5707 0" />
                    <geometry>
		        <cylinder radius="0.01" length="0.005"/>
                    </geometry>
            </collision>
		      <xacro:default_inertial mass="0.002"/>
    	</link>
    	<!--Attach RoboPeak_base to the laser_base-->
    	<joint name="camera_1_joint" type="fixed">
	    <parent link="base_link" />
	    <child link="camera_1"/>
	    <origin xyz=" 0.23 0.12 0.08" rpy="0 0 0" />
    	</joint>
<!--  cam2  -->
     <link name="camera_2">
	    <visual>
	        <origin xyz="0 0 0" rpy="0 1.5707 0" />
	 	    <geometry>
		        <cylinder radius="0.01" length="0.005"/>
		    </geometry>
	    </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 1.5707 0" />
                    <geometry>
		        <cylinder radius="0.01" length="0.005"/>
                    </geometry>
            </collision>
		      <xacro:default_inertial mass="0.002"/>
    	</link>
    	<!--Attach RoboPeak_base to the laser_base-->
    	<joint name="camera_2_joint" type="fixed">
	    <parent link="base_link" />
	    <child link="camera_2"/>
	    <origin xyz=" 0.23 -0.120 0.08" rpy="0 0 0" />
    	</joint>


<!-- wheel powered -->

  <link name="left_wheel_link">

    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.06" length="0.02"/>
      </geometry>
    </collision>
    <visual name="left_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.06" length="0.02"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="1"/>
      <inertia
        ixx=".1" ixy="0.0" ixz="0.0"
        iyy=".1" iyz="0.0"
        izz=".1"/>
    </inertial>
  </link>
  <link name="right_wheel_link">

    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.06" length="0.02"/>
      </geometry>
    </collision>
    <visual name="right_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.06" length="0.02"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="1"/>
      <inertia
        ixx=".1" ixy="0.0" ixz="0.0"
        iyy=".1" iyz="0.0"
        izz=".1"/>
    </inertial>
  </link>

  <joint name="left_wheel" type="continuous">
    <origin xyz="0 0.16 -0.12" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <joint name="right_wheel" type="continuous">
    <origin xyz="0 -0.16 -0.12" rpy="0 0 0"/>
    <child link="right_wheel_link"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>



<!--back wheel powerless -->

  <link name="back_left_wheel_link">

    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.06" length="0.02"/>
      </geometry>
    </collision>
    <visual name="back_left_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.06" length="0.02"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="0.2"/>
      <inertia
        ixx=".01" ixy="0.0" ixz="0.0"
        iyy=".01" iyz="0.0"
        izz=".01"/>
    </inertial>
  </link>
  <link name="back_right_wheel_link">

    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.06" length="0.02"/>
      </geometry>
    </collision>
    <visual name="back_right_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.06" length="0.02"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="0.2"/>
      <inertia
        ixx=".01" ixy="0.0" ixz="0.0"
        iyy=".01" iyz="0.0"
        izz=".01"/>
    </inertial>
  </link>

  <joint name="back_left_wheel" type="continuous">
    <origin xyz="0.18 0.16 -0.12" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="back_left_wheel_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <joint name="back_right_wheel" type="continuous">
    <origin xyz="0.18 -0.16 -0.120000001" rpy="0 0 0"/>
    <child link="back_right_wheel_link"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>


<!--front wheel powerless -->

  <link name="front_left_wheel_link">

    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.06" length="0.02"/>
      </geometry>
    </collision>
    <visual name="front_left_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.06" length="0.02"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="0.2"/>
      <inertia
        ixx=".01" ixy="0.0" ixz="0.0"
        iyy=".01" iyz="0.0"
        izz=".01"/>
    </inertial>
  </link>
  <link name="front_right_wheel_link">

    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.06" length="0.02"/>
      </geometry>
    </collision>
    <visual name="front_right_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.06" length="0.02"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="0.02"/>
      <inertia
        ixx=".01" ixy="0.0" ixz="0.0"
        iyy=".01" iyz="0.0"
        izz=".01"/>
    </inertial>
  </link>

  <joint name="front_left_wheel" type="continuous">
    <origin xyz="-0.18 0.16 -0.12" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="front_left_wheel_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <joint name="front_right_wheel" type="continuous">
    <origin xyz="-0.18 -0.16 -0.12" rpy="0 0 0"/>
    <child link="front_right_wheel_link"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>




</robot>
